[
  {
    "id": "fig-001",
    "name": "Naruto Uzumaki - Action Figure",
    "category": "Figurines",
    "price": 8800,
    "image": "aether-knight.jpg",
    "description": "The figure depicts Naruto standing with his arms confidently crossed, dressed in his signature orange and black outfit from the Kazekage Rescue Arc. His headband features the Hidden Leaf Village symbol, and the sculpt captures the distinctive spiky blond hair and blue eyes.",
    "details": "Dimensions: H=24cm · Polystone · Hand-painted",
    "featured": true,
    "badge": "Limited",
    "stock": 8,
    "sku": "TH-FIG-001"
  },
  {
    "id": "fig-002",
    "name": "Chainsaw Man - Action Figure",
    "category": "Figurines",
    "price": 9999,
    "image": "Chainsaw Man.webp",
    "description": "Chainsaw Man in a dynamic action pose. The character is depicted mid leap, with chainsaws extending from both arms and his head, capturing his distinctive design.",
    "details": "Dimensions: W12 x H16cm · PVC · Display base included",
    "featured": false,
    "badge": "",
    "stock": 20,
    "sku": "TH-FIG-002"
  },
  {
    "id": "fig-003",
    "name": " Yuta Okkotsu - Action Figure",
    "category": "Figurines",
    "price": 8500,
    "image": "Nanami.webp",
    "description": " Yuta  holding a striking sword enveloped in translucent red energy effects. He is dressed in his signature light colored jacket, dark pants, and white sneakers, reflecting his appearance from the movie.",
    "details": "Dimensions: H=19cm · Resin · Limited palette",
    "featured": true,
    "badge": "New",
    "stock": 6,
    "sku": "TH-FIG-003"
  },
  {
    "id": "fig-004",
    "name": "The Beast Titan - Action Figure",
    "category": "Figurines",
    "price": 10800,
    "image": "beast.webp",
    "description": "The Beast Titan in a dynamic pose, with one arm extended and a rock held in his hand, referencing a memorable moment from the series. The sculpt highlights the character’s distinctive fur texture, muscular build, and detailed facial expression.",
    "details": "Dimensions: H=30cm · Polystone · Walnut base",
    "featured": false,
    "badge": "",
    "stock": 14,
    "sku": "TH-FIG-004"
  },
  {
    "id": "toy-001",
    "name": "Super Mario - Plush",
    "category": "Toys",
    "price": 2800,
    "image": "mario.JPG",
    "description": "A soft and cuddly Super Mario plush toy, perfect for fans of all ages.",
    "details": "14 x 8.9 x 24.1 cm · Multicolored · 0.1 kg",
    "featured": true,
    "badge": "",
    "stock": 11,
    "sku": "TH-TOY-001"
  },
  {
    "id": "toy-002",
    "name": "Magnetic Wooden Chess Set",
    "category": "Toys",
    "price": 6800,
    "image": "chess.JPG",
    "description": "A magnetic wooden chess set with a classic design, perfect for both beginners and experienced players. The pieces are crafted from high quality wood and feature a smooth finish, while the magnetic base ensures stability during gameplay.",
    "details": "Ages 8+ · 64 tiles · Wood + magnets",
    "featured": false,
    "badge": "Bestseller",
    "stock": 18,
    "sku": "TH-TOY-002"
  },
  {
    "id": "toy-003",
    "name": "Snoopy - Plush",
    "category": "Toys",
    "price": 1600,
    "image": "snoopy.jpg",
    "description": "This palm sized plush is ideal for gifting or travel, making it a thoughtful surprise for birthdays, holidays, or special occasions.",
    "details": "10.2 x 12.7 x 11.4 cm · Soft plush · Surface wash",
    "featured": false,
    "badge": "",
    "stock": 25,
    "sku": "TH-TOY-003"
  },
  {
    "id": "toy-004",
    "name": "Guess Who - Board Game",
    "category": "Toys",
    "price": 5600,
    "image": "guess.JPG",
    "description": "A classic guessing game where players ask yes or no questions to deduce the identity of their opponent's character. The game features a variety of characters with unique traits, making each round a fun and engaging challenge.",
    "details": "2 Players · Indoor · Ages 6+",
    "featured": false,
    "badge": "",
    "stock": 16,
    "sku": "TH-TOY-004"
  },
  {
    "id": "game-001",
    "name": "Scrabble - Board Game",
    "category": "Board Games",
    "price": 4000,
    "image": "scrabble.jpg",
    "description": "This timeless game offers a traditional Scrabble experience with high quality components, ensuring durability and enjoyable play for years to come..",
    "details": "2–4 players · 75 min · Ages 12+",
    "featured": true,
    "badge": "Bestseller",
    "stock": 9,
    "sku": "TH-GAM-001"
  },
  {
    "id": "game-002",
    "name": "Ludo - Board Game",
    "category": "Board Games",
    "price": 3500,
    "image": "ludo.JPG",
    "description": "A classic board game where players race their four tokens from start to finish based on dice rolls. The game is known for its simple rules and strategic gameplay, making it a favorite for family game nights.",
    "details": "2–4 players · 20 min · Ages 10+",
    "featured": false,
    "badge": "",
    "stock": 13,
    "sku": "TH-GAM-002"
  },
  {
    "id": "game-003",
    "name": "Horse Race - Board Game ",
    "category": "Board Games",
    "price": 4000,
    "image": "horse.JPG",
    "description": "A fast paced horse racing game where players bet on their favorite horses and try to outmaneuver their opponents. The game features colorful horse pieces and a dynamic race track that changes with each playthrough.",
    "details": "2 players · 15 min · Ages 10+",
    "featured": false,
    "badge": "",
    "stock": 15,
    "sku": "TH-GAM-003"
  },
  {
    "id": "game-004",
    "name": "Chutes And Ladders - Board Game",
    "category": "Board Games",
    "price": 2000,
    "image": "ladders.JPG",
    "description": "A classic board game where players navigate a game board filled with chutes and ladders, aiming to reach the finish line first. The game is designed for young players and encourages counting and turn taking skills.",
    "details": "1–4 players · 20 min · Ages 8+",
    "featured": false,
    "badge": "New",
    "stock": 17,
    "sku": "TH-GAM-004"
  },
  {
    "id": "car-001",
    "name": "'Transformer Robot Car",
    "category": "Toy Cars",
    "price": 3000,
    "image": "transformer.JPG",
    "description": "Transformer Robot Bump and Go Car, A toy for Kids Let your kids enjoy this fun car.",
    "details": "21 x 9 x 7 cm ·  · Opening parts",
    "featured": false,
    "badge": "",
    "stock": 10,
    "sku": "TH-CAR-001"
  },
  {
    "id": "car-002",
    "name": "Chevy Bel Air Coupe 1957 ",
    "category": "Toy Cars",
    "price": 12400,
    "image": "bell.JPG",
    "description": "A classic 1957 Chevy Bel Air Coupe diecast model, featuring authentic design details and a high level of craftsmanship. This collectible car is perfect for enthusiasts and collectors who appreciate vintage automotive design.",
    "details": "Scale 1:40 · Diecast metal · Functioning doors",
    "featured": true,
    "badge": "New",
    "stock": 7,
    "sku": "TH-CAR-002"
  },
  {
    "id": "car-003",
    "name": "Lightning McQueen RC Car ",
    "category": "Toy Cars",
    "price": 5200,
    "image": "mcqueen.JPG",
    "description": "A remote controlled Lightning McQueen car from the popular animated movie franchise. This diecast model features authentic design details, including McQueen's signature red paint and racing decals, making it a must-have for fans and collectors.",
    "details": "Scale 1:24 · Plastic · Rubber tyres",
    "featured": false,
    "badge": "",
    "stock": 12,
    "sku": "TH-CAR-003"
  },
  {
    "id": "car-004",
    "name": "Toyota Land Cruiser MN82 RC Car",
    "category": "Toy Cars",
    "price": 20000,
    "image": "land.JPG",
    "description": "A detailed replica of the Toyota Land Cruiser MN82, featuring realistic design elements and functional RC capabilities. This diecast model is perfect for collectors and enthusiasts who appreciate the craftsmanship of scale models.",
    "details": "Scale 1:18 · Diecast metal · Off Road",
    "featured": true,
    "badge": "Limited",
    "stock": 5,
    "sku": "TH-CAR-004"
  }
]
